# Movie Recommendation System using Collaborative Filtering

In [ ]:
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import train_test_split
from surprise import accuracy
import surprise


data = Dataset.load_builtin('ml-100k')

In [3]:
data

In [5]:
# Use the famous SVD algorithm.
algo = SVD()

In [13]:
trainset, testset = train_test_split(data, test_size = 0.2, random_state = 42)

In [19]:
model = algo.fit(trainset)

In [25]:
predictions = model.test(testset)

In [27]:
predictions

[Prediction(uid='907', iid='143', r_ui=5.0, est=4.853234863082919, details={'was_impossible': False}),
 Prediction(uid='371', iid='210', r_ui=4.0, est=4.318952117970097, details={'was_impossible': False}),
 Prediction(uid='218', iid='42', r_ui=4.0, est=3.6123565116527905, details={'was_impossible': False}),
 Prediction(uid='829', iid='170', r_ui=4.0, est=4.026575698454958, details={'was_impossible': False}),
 Prediction(uid='733', iid='277', r_ui=1.0, est=3.077276662606272, details={'was_impossible': False}),
 Prediction(uid='363', iid='1512', r_ui=1.0, est=3.4220551570256603, details={'was_impossible': False}),
 Prediction(uid='193', iid='487', r_ui=5.0, est=3.9564067997206473, details={'was_impossible': False}),
 Prediction(uid='808', iid='313', r_ui=5.0, est=4.830457401580477, details={'was_impossible': False}),
 Prediction(uid='557', iid='682', r_ui=2.0, est=3.586939703919422, details={'was_impossible': False}),
 Prediction(uid='774', iid='196', r_ui=3.0, est=2.5474996635719993, details={'was_impossible': False}),
 Prediction(uid='638', iid='118', r_ui=3.0, est=2.8129217850019517, details={'was_impossible': False}),
 Prediction(uid='632', iid='81', r_ui=5.0, est=3.3538447910563245, details={'was_impossible': False}),
 Prediction(uid='417', iid='200', r_ui=4.0, est=3.581809329992342, details={'was_impossible': False}),
 Prediction(uid='580', iid='471', r_ui=3.0, est=3.7307704016822063, details={'was_impossible': False}),
 Prediction(uid='640', iid='91', r_ui=4.0, est=4.132610556128791, details={'was_impossible': False}),
 Prediction(uid='450', iid='328', r_ui=4.0, est=3.9034345834476993, details={'was_impossible': False}),
 Prediction(uid='596', iid='13', r_ui=2.0, est=3.3981181085852534, details={'was_impossible': False}),
 Prediction(uid='586', iid='467', r_ui=4.0, est=3.477753860198328, details={'was_impossible': False}),
 Prediction(uid='653', iid='502', r_ui=2.0, est=2.8820493241844973, details={'was_impossible': False}),
 Prediction(uid='378', iid='517', r_ui=3.0, est=3.641698072396589, details={'was_impossible': False}),
 Prediction(uid='405', iid='65', r_ui=1.0, est=1.4905859738044258, details={'was_impossible': False}),
 Prediction(uid='279', iid='399', r_ui=4.0, est=3.213848377570871, details={'was_impossible': False}),
 Prediction(uid='327', iid='293', r_ui=3.0, est=3.488153691487663, details={'was_impossible': False}),
 Prediction(uid='346', iid='276', r_ui=1.0, est=2.6665037137721517, details={'was_impossible': False}),
 Prediction(uid='59', iid='928', r_ui=4.0, est=2.7004481486655787, details={'was_impossible': False}),
 Prediction(uid='514', iid='22', r_ui=4.0, est=4.265832507381969, details={'was_impossible': False}),
 Prediction(uid='807', iid='402', r_ui=5.0, est=4.05880195866405, details={'was_impossible': False}),
 Prediction(uid='473', iid='327', r_ui=3.0, est=3.6341344109348905, details={'was_impossible': False}),
 Prediction(uid='342', iid='324', r_ui=1.0, est=2.8218247142998, details={'was_impossible': False}),
 Prediction(uid='269', iid='136', r_ui=4.0, est=3.506776969963371, details={'was_impossible': False}),
 Prediction(uid='654', iid='1', r_ui=4.0, est=3.712451013215357, details={'was_impossible': False}),
 Prediction(uid='250', iid='28', r_ui=4.0, est=4.3791752733037494, details={'was_impossible': False}),
 Prediction(uid='282', iid='689', r_ui=2.0, est=3.18821657992023, details={'was_impossible': False}),
 Prediction(uid='534', iid='619', r_ui=4.0, est=4.133826924415563, details={'was_impossible': False}),
 Prediction(uid='194', iid='481', r_ui=3.0, est=3.22976154270466, details={'was_impossible': False}),
 Prediction(uid='184', iid='118', r_ui=2.0, est=3.2768420507035043, details={'was_impossible': False}),
 Prediction(uid='291', iid='739', r_ui=3.0, est=3.8783338916369825, details={'was_impossible': False}),
 Prediction(uid='293', iid='31', r_ui=2.0, est=3.2982151471022, details={'was_impossible': False}),
 Prediction(uid='943', iid='1028', r_ui=2.0, est=2.823963823178731, details={'was_impossible': False}),
 Prediction(uid='65', iid='69', r_ui=3.0, est=3.8423712160325776, details={'was_impossible': False}),
 Prediction(uid='562', iid='135', r_ui=5.0, est=4.012211031148334, details={'was_impossible': False}),
 Prediction(uid='466', iid='62', r_ui=3.0, est=2.8499017682992447, details={'was_impossible': False}),
 Prediction(uid='847', iid='317', r_ui=3.0, est=3.131296156456843, details={'was_impossible': False}),
 Prediction(uid='650', iid='521', r_ui=3.0, est=3.2281136556324412, details={'was_impossible': False}),
 Prediction(uid='656', iid='326', r_ui=1.0, est=2.4642431479671534, details={'was_impossible': False}),
 Prediction(uid='366', iid='53', r_ui=5.0, est=3.807217423745587, details={'was_impossible': False}),
 Prediction(uid='15', iid='280', r_ui=3.0, est=2.8812607030610664, details={'was_impossible': False}),
 Prediction(uid='474', iid='322', r_ui=4.0, est=3.2138268030061874, details={'was_impossible': False}),
 Prediction(uid='90', iid='905', r_ui=4.0, est=3.7903260075206013, details={'was_impossible': False}),
 Prediction(uid='503', iid='19', r_ui=5.0, est=4.256350237039815, details={'was_impossible': False}),
 Prediction(uid='334', iid='1524', r_ui=4.0, est=3.586639537428728, details={'was_impossible': False}),
 Prediction(uid='90', iid='632', r_ui=5.0, est=4.290222630959233, details={'was_impossible': False}),
 Prediction(uid='406', iid='1118', r_ui=3.0, est=3.3743050835787853, details={'was_impossible': False}),
 Prediction(uid='899', iid='515', r_ui=3.0, est=4.0138606456470365, details={'was_impossible': False}),
 Prediction(uid='13', iid='339', r_ui=3.0, est=2.9963814026757714, details={'was_impossible': False}),
 Prediction(uid='430', iid='19', r_ui=5.0, est=3.965172901846922, details={'was_impossible': False}),
 Prediction(uid='24', iid='729', r_ui=5.0, est=3.9298728371387144, details={'was_impossible': False}),
 Prediction(uid='634', iid='225', r_ui=3.0, est=2.8046795690375315, details={'was_impossible': False}),
 Prediction(uid='727', iid='89', r_ui=5.0, est=4.0312421394012175, details={'was_impossible': False}),
 Prediction(uid='429', iid='596', r_ui=3.0, est=3.5249307887422336, details={'was_impossible': False}),
 Prediction(uid='62', iid='127', r_ui=4.0, est=4.537258010599953, details={'was_impossible': False}),
 Prediction(uid='771', iid='241', r_ui=1.0, est=3.325173956857731, details={'was_impossible': False}),
 Prediction(uid='733', iid='762', r_ui=4.0, est=3.076818785932906, details={'was_impossible': False}),
 Prediction(uid='139', iid='222', r_ui=3.0, est=3.7043303568079198, details={'was_impossible': False}),
 Prediction(uid='916', iid='721', r_ui=4.0, est=3.29600845901451, details={'was_impossible': False}),
 Prediction(uid='402', iid='204', r_ui=5.0, est=4.2153629063581874, details={'was_impossible': False}),
 Prediction(uid='553', iid='136', r_ui=4.0, est=4.2177094690326005, details={'was_impossible': False}),
 Prediction(uid='62', iid='1073', r_ui=4.0, est=3.6759643673699927, details={'was_impossible': False}),
 Prediction(uid='521', iid='271', r_ui=3.0, est=2.7941162917554734, details={'was_impossible': False}),
 Prediction(uid='488', iid='358', r_ui=3.0, est=2.2092988024987354, details={'was_impossible': False}),
 Prediction(uid='7', iid='231', r_ui=3.0, est=2.541784381436308, details={'was_impossible': False}),
 Prediction(uid='346', iid='727', r_ui=1.0, est=3.3096790361671613, details={'was_impossible': False}),
 Prediction(uid='423', iid='823', r_ui=3.0, est=2.880351892993389, details={'was_impossible': False}),
 Prediction(uid='405', iid='575', r_ui=5.0, est=1.8247114483934896, details={'was_impossible': False}),
 Prediction(uid='385', iid='1158', r_ui=5.0, est=2.8075920285230995, details={'was_impossible': False}),
 Prediction(uid='630', iid='125', r_ui=3.0, est=3.657116566251562, details={'was_impossible': False}),
 Prediction(uid='551', iid='125', r_ui=4.0, est=3.681789198942967, details={'was_impossible': False}),
 Prediction(uid='727', iid='183', r_ui=3.0, est=3.268691721981784, details={'was_impossible': False}),
 Prediction(uid='660', iid='810', r_ui=3.0, est=2.0428871941838938, details={'was_impossible': False}),
 Prediction(uid='552', iid='323', r_ui=2.0, est=2.9113748067636633, details={'was_impossible': False}),
 Prediction(uid='13', iid='604', r_ui=5.0, est=3.4410551345911067, details={'was_impossible': False}),
 Prediction(uid='642', iid='812', r_ui=4.0, est=3.2746079279083316, details={'was_impossible': False}),
 Prediction(uid='240', iid='269', r_ui=5.0, est=4.103261102527122, details={'was_impossible': False}),
 Prediction(uid='321', iid='191', r_ui=3.0, est=3.9471964574413865, details={'was_impossible': False}),
 Prediction(uid='85', iid='921', r_ui=3.0, est=3.615352933756597, details={'was_impossible': False}),
 Prediction(uid='671', iid='161', r_ui=5.0, est=3.789856306685206, details={'was_impossible': False}),
 Prediction(uid='253', iid='97', r_ui=4.0, est=4.245286924148632, details={'was_impossible': False}),
 Prediction(uid='605', iid='187', r_ui=5.0, est=4.606689178948788, details={'was_impossible': False}),
 Prediction(uid='472', iid='625', r_ui=4.0, est=4.264981537539352, details={'was_impossible': False}),
 Prediction(uid='56', iid='449', r_ui=5.0, est=3.419840657861106, details={'was_impossible': False}),
 Prediction(uid='881', iid='141', r_ui=3.0, est=3.4572078177106986, details={'was_impossible': False}),
 Prediction(uid='391', iid='318', r_ui=4.0, est=4.273225079048317, details={'was_impossible': False}),
 Prediction(uid='601', iid='387', r_ui=3.0, est=3.2717666534979757, details={'was_impossible': False}),
 Prediction(uid='497', iid='475', r_ui=4.0, est=3.5143162073814658, details={'was_impossible': False}),
 Prediction(uid='327', iid='921', r_ui=4.0, est=3.637972494796529, details={'was_impossible': False}),
 Prediction(uid='200', iid='1033', r_ui=2.0, est=3.2838850728529083, details={'was_impossible': False}),
 Prediction(uid='605', iid='64', r_ui=5.0, est=4.419497745515198, details={'was_impossible': False}),
 Prediction(uid='796', iid='879', r_ui=4.0, est=3.3713696598094476, details={'was_impossible': False}),
 Prediction(uid='214', iid='216', r_ui=4.0, est=3.7573411664845806, details={'was_impossible': False}),
 Prediction(uid='566', iid='161', r_ui=4.0, est=2.700260981932776, details={'was_impossible': False}),
 Prediction(uid='653', iid='423', r_ui=2.0, est=2.776981288152143, details={'was_impossible': False}),
 Prediction(uid='344', iid='216', r_ui=4.0, est=4.006347220481248, details={'was_impossible': False}),
 Prediction(uid='151', iid='664', r_ui=5.0, est=3.665177522204475, details={'was_impossible': False}),
 Prediction(uid='64', iid='751', r_ui=2.0, est=3.398825537309189, details={'was_impossible': False}),
 Prediction(uid='554', iid='87', r_ui=4.0, est=3.914024720827398, details={'was_impossible': False}),
 Prediction(uid='384', iid='327', r_ui=4.0, est=3.9066425462082552, details={'was_impossible': False}),
 Prediction(uid='798', iid='1032', r_ui=3.0, est=2.9268328206751915, details={'was_impossible': False}),
 Prediction(uid='622', iid='90', r_ui=4.0, est=3.4257958853347588, details={'was_impossible': False}),
 Prediction(uid='719', iid='735', r_ui=5.0, est=3.1714480733515438, details={'was_impossible': False}),
 Prediction(uid='424', iid='740', r_ui=5.0, est=3.1312946116184115, details={'was_impossible': False}),
 Prediction(uid='294', iid='358', r_ui=2.0, est=2.920657828052463, details={'was_impossible': False}),
 Prediction(uid='21', iid='396', r_ui=2.0, est=2.926734226324289, details={'was_impossible': False}),
 Prediction(uid='690', iid='197', r_ui=4.0, est=3.5860373889015587, details={'was_impossible': False}),
 Prediction(uid='360', iid='471', r_ui=4.0, est=3.4586254124609175, details={'was_impossible': False}),
 Prediction(uid='734', iid='603', r_ui=4.0, est=4.208127358499377, details={'was_impossible': False}),
 Prediction(uid='521', iid='174', r_ui=4.0, est=3.6511576589917434, details={'was_impossible': False}),
 Prediction(uid='484', iid='300', r_ui=4.0, est=4.099308991248557, details={'was_impossible': False}),
 Prediction(uid='128', iid='50', r_ui=4.0, est=4.566693672694865, details={'was_impossible': False}),
 Prediction(uid='633', iid='921', r_ui=3.0, est=3.7108085718453996, details={'was_impossible': False}),
 Prediction(uid='854', iid='466', r_ui=3.0, est=3.0499860975240494, details={'was_impossible': False}),
 Prediction(uid='493', iid='751', r_ui=5.0, est=3.50439731354622, details={'was_impossible': False}),
 Prediction(uid='504', iid='392', r_ui=5.0, est=3.8429494321797986, details={'was_impossible': False}),
 Prediction(uid='655', iid='318', r_ui=4.0, est=3.7996269562970015, details={'was_impossible': False}),
 Prediction(uid='650', iid='157', r_ui=3.0, est=3.040581441195765, details={'was_impossible': False}),
 Prediction(uid='104', iid='273', r_ui=3.0, est=2.9551181175400973, details={'was_impossible': False}),
 Prediction(uid='872', iid='117', r_ui=4.0, est=4.207972507661722, details={'was_impossible': False}),
 Prediction(uid='276', iid='1170', r_ui=4.0, est=3.053740192563749, details={'was_impossible': False}),
 Prediction(uid='146', iid='258', r_ui=4.0, est=3.5466425635843755, details={'was_impossible': False}),
 Prediction(uid='222', iid='1066', r_ui=1.0, est=2.8523098837390486, details={'was_impossible': False}),
 Prediction(uid='380', iid='199', r_ui=3.0, est=3.5441354277001973, details={'was_impossible': False}),
 Prediction(uid='618', iid='195', r_ui=3.0, est=4.087679675285708, details={'was_impossible': False}),
 Prediction(uid='358', iid='1266', r_ui=4.0, est=3.5828837638978017, details={'was_impossible': False}),
 Prediction(uid='871', iid='813', r_ui=3.0, est=3.902345892656114, details={'was_impossible': False}),
 Prediction(uid='234', iid='174', r_ui=3.0, est=3.6806338695092653, details={'was_impossible': False}),
 Prediction(uid='912', iid='15', r_ui=4.0, est=3.6152857566701537, details={'was_impossible': False}),
 Prediction(uid='75', iid='237', r_ui=2.0, est=3.580878501110656, details={'was_impossible': False}),
 Prediction(uid='713', iid='270', r_ui=2.0, est=3.1187285299568948, details={'was_impossible': False}),
 Prediction(uid='251', iid='33', r_ui=3.0, est=3.726425433692864, details={'was_impossible': False}),
 Prediction(uid='275', iid='199', r_ui=4.0, est=3.561701899999218, details={'was_impossible': False}),
 Prediction(uid='766', iid='91', r_ui=5.0, est=3.452920989984616, details={'was_impossible': False}),
 Prediction(uid='22', iid='204', r_ui=5.0, est=4.110997734315063, details={'was_impossible': False}),
 Prediction(uid='487', iid='591', r_ui=2.0, est=3.5342445256281536, details={'was_impossible': False}),
 Prediction(uid='827', iid='316', r_ui=3.0, est=4.069793432755672, details={'was_impossible': False}),
 Prediction(uid='919', iid='22', r_ui=5.0, est=4.07554047105388, details={'was_impossible': False}),
 Prediction(uid='637', iid='274', r_ui=5.0, est=2.6225784746462932, details={'was_impossible': False}),
 Prediction(uid='666', iid='856', r_ui=5.0, est=3.797513072485895, details={'was_impossible': False}),
 Prediction(uid='349', iid='458', r_ui=4.0, est=3.1131156724033535, details={'was_impossible': False}),
 Prediction(uid='880', iid='1197', r_ui=3.0, est=4.086088968075417, details={'was_impossible': False}),
 Prediction(uid='30', iid='892', r_ui=4.0, est=2.845994125863803, details={'was_impossible': False}),
 Prediction(uid='716', iid='213', r_ui=5.0, est=4.002825448298817, details={'was_impossible': False}),
 Prediction(uid='235', iid='70', r_ui=5.0, est=3.6596597198031793, details={'was_impossible': False}),
 Prediction(uid='291', iid='1042', r_ui=4.0, est=3.514172629826581, details={'was_impossible': False}),
 Prediction(uid='655', iid='311', r_ui=3.0, est=3.301104710348352, details={'was_impossible': False}),
 Prediction(uid='387', iid='642', r_ui=4.0, est=3.7548007192526116, details={'was_impossible': False}),
 Prediction(uid='109', iid='31', r_ui=4.0, est=3.7664325175441262, details={'was_impossible': False}),
 Prediction(uid='484', iid='69', r_ui=5.0, est=4.509880495646712, details={'was_impossible': False}),
 Prediction(uid='393', iid='7', r_ui=4.0, est=3.46075423833671, details={'was_impossible': False}),
 Prediction(uid='314', iid='53', r_ui=1.0, est=3.4161232438421663, details={'was_impossible': False}),
 Prediction(uid='845', iid='1394', r_ui=4.0, est=2.7867973618490685, details={'was_impossible': False}),
 Prediction(uid='532', iid='311', r_ui=2.0, est=4.5205856162821085, details={'was_impossible': False}),
 Prediction(uid='195', iid='558', r_ui=3.0, est=3.4820671787328, details={'was_impossible': False}),
 Prediction(uid='89', iid='151', r_ui=5.0, est=3.9575165912427672, details={'was_impossible': False}),
 Prediction(uid='824', iid='243', r_ui=1.0, est=2.6846129732982194, details={'was_impossible': False}),
 Prediction(uid='632', iid='11', r_ui=4.0, est=3.5882860831485295, details={'was_impossible': False}),
 Prediction(uid='393', iid='412', r_ui=3.0, est=2.162398915581869, details={'was_impossible': False}),
 Prediction(uid='887', iid='121', r_ui=5.0, est=4.842581454175293, details={'was_impossible': False}),
 Prediction(uid='682', iid='412', r_ui=1.0, est=1.999184286614226, details={'was_impossible': False}),
 Prediction(uid='406', iid='210', r_ui=5.0, est=3.7806009124391577, details={'was_impossible': False}),
 Prediction(uid='795', iid='552', r_ui=2.0, est=2.6589464883863725, details={'was_impossible': False}),
 Prediction(uid='774', iid='546', r_ui=1.0, est=1.8361425536648002, details={'was_impossible': False}),
 Prediction(uid='47', iid='304', r_ui=3.0, est=3.589907214044142, details={'was_impossible': False}),
 Prediction(uid='514', iid='15', r_ui=4.0, est=4.013528897453905, details={'was_impossible': False}),
 Prediction(uid='804', iid='175', r_ui=4.0, est=3.6582244076323245, details={'was_impossible': False}),
 Prediction(uid='804', iid='1056', r_ui=4.0, est=3.474923773637704, details={'was_impossible': False}),
 Prediction(uid='21', iid='243', r_ui=2.0, est=1.800697510883042, details={'was_impossible': False}),
 Prediction(uid='618', iid='778', r_ui=3.0, est=3.581236315757881, details={'was_impossible': False}),
 Prediction(uid='151', iid='222', r_ui=5.0, est=3.6276801835226093, details={'was_impossible': False}),
 Prediction(uid='224', iid='583', r_ui=1.0, est=2.892839403971769, details={'was_impossible': False}),
 Prediction(uid='283', iid='709', r_ui=5.0, est=4.741066476368565, details={'was_impossible': False}),
 Prediction(uid='504', iid='185', r_ui=5.0, est=4.38735887695882, details={'was_impossible': False}),
 Prediction(uid='553', iid='135', r_ui=4.0, est=3.6459207869598904, details={'was_impossible': False}),
 Prediction(uid='846', iid='203', r_ui=5.0, est=4.1847325527246015, details={'was_impossible': False}),
 Prediction(uid='773', iid='52', r_ui=3.0, est=3.420278494499975, details={'was_impossible': False}),
 Prediction(uid='385', iid='384', r_ui=1.0, est=2.568932853788096, details={'was_impossible': False}),
 Prediction(uid='346', iid='720', r_ui=2.0, est=3.0860147905343895, details={'was_impossible': False}),
 Prediction(uid='373', iid='366', r_ui=4.0, est=3.376666252148935, details={'was_impossible': False}),
 Prediction(uid='881', iid='474', r_ui=3.0, est=3.549362575274931, details={'was_impossible': False}),
 Prediction(uid='537', iid='845', r_ui=2.0, est=2.455146401846833, details={'was_impossible': False}),
 Prediction(uid='474', iid='50', r_ui=5.0, est=4.551109237812942, details={'was_impossible': False}),
 Prediction(uid='293', iid='77', r_ui=2.0, est=2.5572092178763173, details={'was_impossible': False}),
 Prediction(uid='542', iid='435', r_ui=4.0, est=3.8092845278344516, details={'was_impossible': False}),
 Prediction(uid='262', iid='111', r_ui=4.0, est=2.9199388752297715, details={'was_impossible': False}),
 Prediction(uid='109', iid='1210', r_ui=3.0, est=2.869667969836427, details={'was_impossible': False}),

In [35]:
rmse = accuracy.rmse(predictions)

RMSE: 0.9352

In [37]:
mae = accuracy.mae(predictions)

MAE:  0.7365

In [39]:
mse = accuracy.mse(predictions)

MSE: 0.8747

In [41]:
import pandas as pd
import numpy as np

In [43]:
df1 = pd.read_csv(r'/Users/mac/Downloads/ml-20m/ratings.csv')
df2 = pd.read_csv(r'/Users/mac/Downloads/ml-20m/movies.csv')

In [44]:
df1.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [47]:
df2.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [49]:
df = df1.merge(df2, on = 'movieId')

In [51]:
df

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,1112486027,Jumanji (1995),Adventure|Children|Fantasy
1,5,2,3.0,851527569,Jumanji (1995),Adventure|Children|Fantasy
2,13,2,3.0,849082742,Jumanji (1995),Adventure|Children|Fantasy
3,29,2,3.0,835562174,Jumanji (1995),Adventure|Children|Fantasy
4,34,2,3.0,846509384,Jumanji (1995),Adventure|Children|Fantasy
...,...,...,...,...,...,...
20000258,138301,121017,3.5,1420558479,The Gentleman from Epsom (1962),Comedy|Crime
20000259,138301,121019,4.5,1420558606,The Great Spy Chase (1964),Action|Comedy|Thriller
20000260,138301,121021,4.5,1420558687,Taxi for Tobruk (1961),Drama|War
20000261,138406,110167,4.5,1396184127,"Judge and the Assassin, The (Juge et l'assassi...",Crime|Drama
20000262,138406,110510,4.5,1397597539,Série noire (1979),Film-Noir

In [53]:
df.shape

(20000263, 6)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
 4   title      object
 5   genres     object
dtypes: float64(1), int64(3), object(2)
memory usage: 915.5+ MB

In [59]:
df = df.drop(columns= 'timestamp')

In [63]:
df.isnull().sum()

userId     0
movieId    0
rating     0
title      0
genres     0
dtype: int64

In [65]:
df_surprise = df[['userId', 'movieId', 'rating']]

In [67]:
df_surprise

          userId  movieId  rating
0              1        2     3.5
1              5        2     3.0
2             13        2     3.0
3             29        2     3.0
4             34        2     3.0
...          ...      ...     ...
20000258  138301   121017     3.5
20000259  138301   121019     4.5
20000260  138301   121021     4.5
20000261  138406   110167     4.5
20000262  138406   110510     4.5

[20000263 rows x 3 columns]

In [69]:
df_surprise.describe()

             userId       movieId        rating
count  2.000026e+07  2.000026e+07  2.000026e+07
mean   6.904587e+04  9.041567e+03  3.525529e+00
std    4.003863e+04  1.978948e+04  1.051989e+00
min    1.000000e+00  1.000000e+00  5.000000e-01
25%    3.439500e+04  9.020000e+02  3.000000e+00
50%    6.914100e+04  2.167000e+03  3.500000e+00
75%    1.036370e+05  4.770000e+03  4.000000e+00
max    1.384930e+05  1.312620e+05  5.000000e+00

In [77]:
reader = surprise.Reader(rating_scale = (0, 5.0))

In [83]:
data = Dataset.load_from_df(df_surprise, reader)

In [85]:
data

In [87]:
trainset, testset = train_test_split(data, test_size = 0.2, random_state = 42)

In [88]:
algo = SVD()

In [91]:
model = algo.fit(trainset)

In [123]:
predictions = model.test(testset)

In [99]:
rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

RMSE: 0.7858
MAE:  0.5980

In [101]:
all_movies = df['movieId'].unique()

In [149]:
user_id = 138301

In [151]:
rated_movies = df[df['userId'] == user_id]['movieId']

In [152]:
rated_movies

22214            2
30750           29
75679           32
118930          47
165931          50
             ...
20000256    113539
20000257    118856
20000258    121017
20000259    121019
20000260    121021
Name: movieId, Length: 1072, dtype: int64

In [155]:
unrated_movies = []

In [157]:
for movie in all_movies:
    if movie not in rated_movies.values:
        unrated_movies.append(movie)

In [159]:
predictions = []
for movie_id in unrated_movies:
    pred = model.predict(user_id, movie_id)
    predictions.append(pred)

In [161]:
predictions

[Prediction(uid=138301, iid=112, r_ui=None, est=2.8663975852382237, details={'was_impossible': False}),
 Prediction(uid=138301, iid=151, r_ui=None, est=3.500663544888524, details={'was_impossible': False}),
 Prediction(uid=138301, iid=318, r_ui=None, est=4.211000148816986, details={'was_impossible': False}),
 Prediction(uid=138301, iid=337, r_ui=None, est=3.7536302145278264, details={'was_impossible': False}),
 Prediction(uid=138301, iid=653, r_ui=None, est=2.6784698840253167, details={'was_impossible': False}),
 Prediction(uid=138301, iid=919, r_ui=None, est=3.1945089010781382, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1009, r_ui=None, est=2.8225099105436846, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1097, r_ui=None, est=2.83476404923528, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1215, r_ui=None, est=3.631943893459041, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1217, r_ui=None, est=4.118939365912229, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1219, r_ui=None, est=3.9020690993921963, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1243, r_ui=None, est=3.9475631079823374, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1258, r_ui=None, est=4.1819667930635855, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1259, r_ui=None, est=3.7704691623567492, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1261, r_ui=None, est=3.426146775071246, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1266, r_ui=None, est=4.2968711911836674, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1278, r_ui=None, est=3.8456043548101384, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1321, r_ui=None, est=3.4167911058511686, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1333, r_ui=None, est=3.8212373317815227, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1348, r_ui=None, est=3.9139731432151295, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1350, r_ui=None, est=3.30487036007826, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1358, r_ui=None, est=3.880890318603926, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1374, r_ui=None, est=3.4126217465834805, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1387, r_ui=None, est=3.3251234751682666, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1525, r_ui=None, est=2.237668745799561, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1750, r_ui=None, est=1.6880389552746513, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1848, r_ui=None, est=2.3123170004259834, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1920, r_ui=None, est=2.49497489846296, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1967, r_ui=None, est=3.415073570832212, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1994, r_ui=None, est=2.9142777340843913, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1997, r_ui=None, est=3.5654292914303305, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2100, r_ui=None, est=2.399739741189034, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2118, r_ui=None, est=3.709785208066482, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2138, r_ui=None, est=3.463309108485259, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2140, r_ui=None, est=3.255216491837798, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2143, r_ui=None, est=3.0716674721710118, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2173, r_ui=None, est=3.4218104004853753, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2193, r_ui=None, est=3.1756132280404223, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2253, r_ui=None, est=3.2437514495769175, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2644, r_ui=None, est=3.0350559450757753, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2648, r_ui=None, est=3.5133225447743874, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2664, r_ui=None, est=3.6634813389966903, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2683, r_ui=None, est=2.776832998680721, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2692, r_ui=None, est=3.8538267920504565, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2804, r_ui=None, est=3.3310893050719663, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2872, r_ui=None, est=3.4144386143186223, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2918, r_ui=None, est=3.7502180411801245, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2947, r_ui=None, est=3.586984090055237, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2968, r_ui=None, est=3.6296390643430363, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3000, r_ui=None, est=4.138169676470193, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3030, r_ui=None, est=4.324915487058807, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3037, r_ui=None, est=4.044113495558365, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3153, r_ui=None, est=3.1968524205327054, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3265, r_ui=None, est=4.040727193210489, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3438, r_ui=None, est=2.8220560560957457, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3476, r_ui=None, est=3.959324087005233, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3479, r_ui=None, est=3.171545742659913, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3489, r_ui=None, est=3.061018324578705, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3499, r_ui=None, est=3.5652164237660546, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3889, r_ui=None, est=1.6799254130294181, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3932, r_ui=None, est=3.286466758276825, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3997, r_ui=None, est=1.5628689798688467, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4105, r_ui=None, est=3.5148409636134015, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4128, r_ui=None, est=3.277794748973379, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4133, r_ui=None, est=1.9691444024632856, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4306, r_ui=None, est=2.659306223314565, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4446, r_ui=None, est=2.229147822859001, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4571, r_ui=None, est=3.2805433358677547, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4754, r_ui=None, est=3.816001479968552, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4896, r_ui=None, est=2.3852196595049824, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4911, r_ui=None, est=3.42414571788696, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4915, r_ui=None, est=2.817430533948483, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4941, r_ui=None, est=3.1239861307306542, details={'was_impossible': False}),
 Prediction(uid=138301, iid=4980, r_ui=None, est=3.1585142473218313, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5026, r_ui=None, est=3.3342822930016784, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5039, r_ui=None, est=3.01048721124122, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5040, r_ui=None, est=2.6781975036297543, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5146, r_ui=None, est=3.230339045871605, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5171, r_ui=None, est=2.1616824183581502, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5540, r_ui=None, est=3.043316905206911, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5679, r_ui=None, est=2.5935822370002564, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5797, r_ui=None, est=3.6711923257831653, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5816, r_ui=None, est=2.3082641881794514, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5898, r_ui=None, est=2.935103155665491, details={'was_impossible': False}),
 Prediction(uid=138301, iid=5999, r_ui=None, est=2.2582772970423557, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6093, r_ui=None, est=3.336684418027801, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6242, r_ui=None, est=3.098448637625124, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6333, r_ui=None, est=2.7844122825033546, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6539, r_ui=None, est=2.716175000018969, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6754, r_ui=None, est=2.4664166515468287, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6755, r_ui=None, est=3.676930759650185, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6774, r_ui=None, est=3.809281397836406, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6834, r_ui=None, est=2.7184699263612226, details={'was_impossible': False}),
 Prediction(uid=138301, iid=6888, r_ui=None, est=2.171810919585175, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7001, r_ui=None, est=3.8291513020690555, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7045, r_ui=None, est=3.184428928172952, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7046, r_ui=None, est=3.0582864523396407, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7164, r_ui=None, est=2.5843207717701406, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7247, r_ui=None, est=3.0335167916627173, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7387, r_ui=None, est=3.7871089252453043, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7389, r_ui=None, est=2.7435154342106167, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7449, r_ui=None, est=1.8640426383805084, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7454, r_ui=None, est=1.9158860306752699, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7482, r_ui=None, est=3.7233251838460584, details={'was_impossible': False}),
 Prediction(uid=138301, iid=7757, r_ui=None, est=3.462936250472912, details={'was_impossible': False}),
 Prediction(uid=138301, iid=8368, r_ui=None, est=2.5652606016471835, details={'was_impossible': False}),
 Prediction(uid=138301, iid=8482, r_ui=None, est=3.7218295147842984, details={'was_impossible': False}),
 Prediction(uid=138301, iid=8507, r_ui=None, est=3.7514571072328358, details={'was_impossible': False}),
 Prediction(uid=138301, iid=8636, r_ui=None, est=2.5182185535803017, details={'was_impossible': False}),
 Prediction(uid=138301, iid=8690, r_ui=None, est=3.681126921588628, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3, r_ui=None, est=2.7363266940899695, details={'was_impossible': False}),
 Prediction(uid=138301, iid=62, r_ui=None, est=2.658633572436349, details={'was_impossible': False}),
 Prediction(uid=138301, iid=242, r_ui=None, est=3.0507869276214516, details={'was_impossible': False}),
 Prediction(uid=138301, iid=266, r_ui=None, est=3.043012797218052, details={'was_impossible': False}),
 Prediction(uid=138301, iid=469, r_ui=None, est=3.399057504649864, details={'was_impossible': False}),
 Prediction(uid=138301, iid=891, r_ui=None, est=1.7894038821125893, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1121, r_ui=None, est=2.743223142951923, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1210, r_ui=None, est=3.503603397940713, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1327, r_ui=None, est=2.695006847002954, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1356, r_ui=None, est=3.2623983702985146, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1965, r_ui=None, est=3.8469030417791243, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1969, r_ui=None, est=1.9351045288836772, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1970, r_ui=None, est=2.30344773051607, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1971, r_ui=None, est=2.072825315856418, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1972, r_ui=None, est=1.8472112086340111, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1973, r_ui=None, est=1.9449068674993306, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1974, r_ui=None, est=2.3020760911175353, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1986, r_ui=None, est=1.6841317289856494, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2454, r_ui=None, est=3.45171064586559, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2455, r_ui=None, est=3.5042415941426794, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2948, r_ui=None, est=3.5445769616182337, details={'was_impossible': False}),
 Prediction(uid=138301, iid=2951, r_ui=None, est=3.9946479855676973, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3150, r_ui=None, est=3.77252470263252, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3159, r_ui=None, est=3.3841022335326882, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3173, r_ui=None, est=3.202726255985756, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3450, r_ui=None, est=2.802842363469862, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3513, r_ui=None, est=2.7270115239798556, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3534, r_ui=None, est=2.7203437354908373, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3555, r_ui=None, est=2.6616232150639547, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3565, r_ui=None, est=2.4052809643098163, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3917, r_ui=None, est=2.860168138040073, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3918, r_ui=None, est=2.674780062028931, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3923, r_ui=None, est=2.209640436010796, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3926, r_ui=None, est=3.4664265287945315, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3927, r_ui=None, est=3.535220916871658, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3928, r_ui=None, est=3.2845270787162257, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3930, r_ui=None, est=3.3913361865974, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3937, r_ui=None, est=2.625139629634962, details={'was_impossible': False}),
 Prediction(uid=138301, iid=3959, r_ui=None, est=3.720744896320179, details={'was_impossible': False}),
 Prediction(uid=138301, iid=24, r_ui=None, est=2.553345163925809, details={'was_impossible': False}),
 Prediction(uid=138301, iid=160, r_ui=None, est=2.30378185188598, details={'was_impossible': False}),
 Prediction(uid=138301, iid=175, r_ui=None, est=3.6462640677743168, details={'was_impossible': False}),
 Prediction(uid=138301, iid=196, r_ui=None, est=2.6061362944344233, details={'was_impossible': False}),
 Prediction(uid=138301, iid=329, r_ui=None, est=2.97483567898099, details={'was_impossible': False}),
 Prediction(uid=138301, iid=440, r_ui=None, est=2.9367737181123035, details={'was_impossible': False}),
 Prediction(uid=138301, iid=457, r_ui=None, est=3.5362621072601264, details={'was_impossible': False}),
 Prediction(uid=138301, iid=490, r_ui=None, est=3.2927643468515386, details={'was_impossible': False}),
 Prediction(uid=138301, iid=512, r_ui=None, est=2.8511181512369212, details={'was_impossible': False}),
 Prediction(uid=138301, iid=610, r_ui=None, est=3.416446387046287, details={'was_impossible': False}),
 Prediction(uid=138301, iid=718, r_ui=None, est=3.8854188011359563, details={'was_impossible': False}),
 Prediction(uid=138301, iid=788, r_ui=None, est=2.445447357975184, details={'was_impossible': False}),
 Prediction(uid=138301, iid=858, r_ui=None, est=4.536782666686129, details={'was_impossible': False}),
 Prediction(uid=138301, iid=905, r_ui=None, est=3.7886124790579823, details={'was_impossible': False}),
 Prediction(uid=138301, iid=953, r_ui=None, est=3.211131597690552, details={'was_impossible': False}),
 Prediction(uid=138301, iid=968, r_ui=None, est=3.6936289969069724, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1037, r_ui=None, est=2.800571353895797, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1073, r_ui=None, est=3.2510910656354595, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1077, r_ui=None, est=4.071882654874084, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1084, r_ui=None, est=3.935403535073524, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1094, r_ui=None, est=3.370707631407044, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1103, r_ui=None, est=3.5691308021720727, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1125, r_ui=None, est=3.6377243079454176, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1188, r_ui=None, est=2.9691774551548282, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1221, r_ui=None, est=4.530391442495988, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1228, r_ui=None, est=4.256796878620577, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1230, r_ui=None, est=4.381637916453872, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1242, r_ui=None, est=3.4157797021056244, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1257, r_ui=None, est=3.757687039671656, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1276, r_ui=None, est=4.079899714974385, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1288, r_ui=None, est=4.00876080457326, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1307, r_ui=None, est=3.239444971093189, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1330, r_ui=None, est=2.9794029696000903, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1345, r_ui=None, est=3.2430245334802716, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1372, r_ui=None, est=3.1940960719852214, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1373, r_ui=None, est=2.809199908632275, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1375, r_ui=None, est=2.990002176905526, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1376, r_ui=None, est=3.02297799413531, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1603, r_ui=None, est=2.6050822663753412, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1674, r_ui=None, est=3.437118122821249, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1762, r_ui=None, est=2.3697758515825087, details={'was_impossible': False}),
 Prediction(uid=138301, iid=1831, r_ui=None, est=1.7189929059423221, details={'was_impossible': False}),

In [163]:
recc = sorted(predictions, key = lambda x: x.est, reverse = True)

In [165]:
top_n = recc[:20]

In [167]:
for pred in top_n:
    title = df[df['movieId'] == pred.iid]['title'].values[0]
    print(f'Reccommended: {title}: predicted rating: {pred.est:.2f}')

Reccommended: Louis C.K.: Live at the Beacon Theater (2011): predicted rating: 4.84
Reccommended: Land and Freedom (Tierra y libertad) (1995): predicted rating: 4.81
Reccommended: Louis C.K.: Shameless (2007): predicted rating: 4.73
Reccommended: 8 1/2 (8½) (1963): predicted rating: 4.70
Reccommended: Cosmos (1980): predicted rating: 4.67
Reccommended: Naked (1993): predicted rating: 4.63
Reccommended: Louis C.K.: Chewed Up (2008): predicted rating: 4.58
Reccommended: Louis C.K.: Hilarious (2010): predicted rating: 4.58
Reccommended: Decalogue, The (Dekalog) (1989): predicted rating: 4.55
Reccommended: Godfather, The (1972): predicted rating: 4.54
Reccommended: Godfather: Part II, The (1974): predicted rating: 4.53
Reccommended: Louis C.K.: Oh My God (2013): predicted rating: 4.51
Reccommended: Trial, The (Procès, Le) (1962): predicted rating: 4.51
Reccommended: Harakiri (Seppuku) (1962): predicted rating: 4.50
Reccommended: Chungking Express (Chung Hing sam lam) (1994): predicted rating: 4.49
Reccommended: Stardust Memories (1980): predicted rating: 4.48
Reccommended: Taxi Driver (1976): predicted rating: 4.48
Reccommended: Fantastic Planet, The (Planète sauvage, La) (1973): predicted rating: 4.48
Reccommended: Down by Law (1986): predicted rating: 4.47
Reccommended: Autumn Sonata (Höstsonaten) (1978): predicted rating: 4.46